after-startup-command = [
  'exec-and-forget borders inactive_color=0xFF5D3EA8 active_color=0xFF7dcfff width=5.0 hidpi=on style=round',
]

# Start AeroSpace at login
start-at-login = false

#. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'
# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 20
inner.vertical = 20
outer.right = [{ monitor.'DeskPad Display' = 0 }, { monitor.main = 300 }, 24]
outer.left = [{ monitor.'DeskPad Display' = 0 }, { monitor.main = 300 }, 24]
outer.bottom = 10
outer.top = 10

# See https://nikitabobko.github.io/AeroSpace/guide#exec-env-vars
[exec] # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true # If you don't touch "exec" section,
[exec.env-vars] # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
# See: https://nikitabobko.github.io/AeroSpace/commands#mode

alt-ctrl-cmd-h = 'focus left'
alt-ctrl-cmd-j = 'focus down'
alt-ctrl-cmd-k = 'focus up'
alt-ctrl-cmd-l = 'focus right'
alt-ctrl-cmd-minus = 'layout floating tiling'
alt-ctrl-cmd-period = 'resize width -100'
alt-ctrl-cmd-comma = 'resize width +100'
alt-ctrl-cmd-u = 'resize width 2400'
alt-ctrl-cmd-o = 'fullscreen --no-outer-gaps'

alt-shift-semicolon = 'mode service'
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-ctrl-cmd-a = 'workspace Arc'
alt-ctrl-cmd-s = 'workspace Slack'
alt-ctrl-cmd-g = 'workspace Ghostty'
alt-ctrl-cmd-m = 'workspace Messaging'
alt-ctrl-cmd-i = 'workspace IntelliJ'
alt-ctrl-cmd-v = 'workspace VSCode'
alt-ctrl-cmd-p = 'workspace Postico'
alt-ctrl-cmd-d = 'workspace Deskpad'
alt-ctrl-cmd-r = 'workspace Reclaim'
alt-ctrl-cmd-t = 'workspace Tools'
alt-ctrl-cmd-e = 'workspace EverythingElse'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-cmd-ctrl-a = 'move-node-to-workspace Arc'
alt-shift-cmd-ctrl-s = 'move-node-to-workspace Slack'
alt-shift-cmd-ctrl-g = 'move-node-to-workspace Ghostty'
alt-shift-cmd-ctrl-m = 'move-node-to-workspace Messaging'
alt-shift-cmd-ctrl-i = 'move-node-to-workspace IntelliJ'
alt-shift-cmd-ctrl-v = 'move-node-to-workspace VSCode'
alt-shift-cmd-ctrl-p = 'move-node-to-workspace Postico'
alt-shift-cmd-ctrl-d = 'move-node-to-workspace Deskpad'
alt-shift-cmd-ctrl-r = 'move-node-to-workspace Reclaim'
alt-shift-cmd-ctrl-t = 'move-node-to-workspace Tools'
alt-shift-cmd-ctrl-e = 'move-node-to-workspace EverythingElse'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

[workspace-to-monitor-force-assignment]
Arc = ['main', 'built-in']
Slack = ['main', 'built-in']
Ghostty = ['DeskPad Display', 'main']
Messaging = ['main', 'built-in']
IntelliJ = ['DeskPad Display', 'main']
VSCode = ['DeskPad Display', 'main']
Postico = ['DeskPad Display', 'main']
Deskpad = ['main']
Reclaim = ['main']
Tools = ['main']
EverythingElse = ['main']

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = [
  'layout floating tiling',
  'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-name-regex-substring = 'Arc'
run = ['move-node-to-workspace Arc']

[[on-window-detected]]
if.app-name-regex-substring = 'Zen'
run = ['move-node-to-workspace Arc']

[[on-window-detected]]
if.app-name-regex-substring = 'Slack'
run = ['move-node-to-workspace Slack']

[[on-window-detected]]
if.app-name-regex-substring = "Ghostty"
run = ["move-node-to-workspace Ghostty"]

[[on-window-detected]]
if.app-name-regex-substring = 'WhatsApp'
run = ['move-node-to-workspace Messaging']

[[on-window-detected]]
if.app-name-regex-substring = 'Messages'
run = ['move-node-to-workspace Messaging']

[[on-window-detected]]
if.app-name-regex-substring = 'Intellij'
run = ['move-node-to-workspace IntelliJ']

[[on-window-detected]]
if.app-name-regex-substring = 'Code'
run = ['move-node-to-workspace VSCode']

[[on-window-detected]]
if.app-name-regex-substring = 'Todoist'
run = ['move-node-to-workspace Tools']

[[on-window-detected]]
if.app-name-regex-substring = 'Reclaim'
run = ['move-node-to-workspace Reclaim']

[[on-window-detected]]
if.app-name-regex-substring = 'Postico'
run = ['move-node-to-workspace Postico']

[[on-window-detected]]
if.app-name-regex-substring = 'Deskpad'
run = ['layout tiling', 'move-node-to-workspace Deskpad']

[[on-window-detected]]
if.app-name-regex-substring = 'Google Gemini'
run = ['move-node-to-workspace Tools']

[[on-window-detected]]
if.app-id = "com.1password.1password"
# if.app-name-regex-substring = '1Password'
run = ['layout floating']

[[on-window-detected]]
if.app-name-regex-substring = 'Gmail'
run = ['move-node-to-workspace Reclaim']

[[on-window-detected]]
if.app-name-regex-substring = 'Music'
run = ['move-node-to-workspace Tools']

[[on-window-detected]]
if.app-name-regex-substring = 'MOTIV Mix'
run = ['move-node-to-workspace EverythingElse']

[[on-window-detected]]
if.app-name-regex-substring = 'CatoClient'
run = ['move-node-to-workspace EverythingElse']

# [[on-window-detected]]
# if.app-name-regex-substring = 'Docker'
# run = ['move-node-to-workspace 6']

# [[on-window-detected]]
# if.app-name-regex-substring = 'Postman'
# run = ['move-node-to-workspace 8']

# [[on-window-detected]]
# if.app-name-regex-substring = 'Vial Web'
# run = ['move-node-to-workspace 10']

# [[on-window-detected]]
# if.app-name-regex-substring = 'Gmail'
# run = ['move-node-to-workspace 11']

# [[on-window-detected]]
# if.app-name-regex-substring = 'Google Calendar'
# run = ['move-node-to-workspace 11']

# [[on-window-detected]]
# if.app-name-regex-substring = 'Confluence PWA'
# run = ['move-node-to-workspace 12']

# [[on-window-detected]]
# if.app-name-regex-substring = 'Jira PWA'
# run = ['move-node-to-workspace 13']

# [[on-window-detected]]
# if.app-name-regex-substring = 'Youtube Music'
# run = ['move-node-to-workspace 5']

# [[on-window-detected]]
# if.app-name-regex-substring = 'GibHub'
# run = ['move-node-to-workspace 16']
