after-startup-command = [
  'exec-and-forget borders inactive_color=0xFF5D3EA8 active_color=0xFF7dcfff width=5.0 hidpi=on style=round',
]

[gaps]
inner.horizontal = 20
inner.vertical = 20
outer.right = [{ monitor.'DeskPad Display' = 0 }, { monitor.main = 300 }, 24]
outer.left = [{ monitor.'DeskPad Display' = 0 }, { monitor.main = 300 }, 24]
outer.bottom = 10
outer.top = 10

# TODO: check if this section is actually needed
# See https://nikitabobko.github.io/AeroSpace/guide#exec-env-vars
[exec] # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true # If you don't touch "exec" section,
[exec.env-vars] # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]
alt-ctrl-cmd-h = 'focus left'
alt-ctrl-cmd-j = 'focus down'
alt-ctrl-cmd-k = 'focus up'
alt-ctrl-cmd-l = 'focus right'
alt-ctrl-cmd-minus = 'layout floating tiling'
alt-ctrl-cmd-period = 'resize width -100'
alt-ctrl-cmd-comma = 'resize width +100'
alt-ctrl-cmd-u = 'resize width 2400'
alt-ctrl-cmd-o = 'fullscreen --no-outer-gaps'

alt-ctrl-cmd-a = 'workspace Arc'
alt-ctrl-cmd-s = 'workspace Slack'
alt-ctrl-cmd-g = 'workspace Ghostty'
alt-ctrl-cmd-m = 'workspace Messaging'
alt-ctrl-cmd-i = 'workspace IntelliJ'
alt-ctrl-cmd-v = 'workspace VSCode'
alt-ctrl-cmd-p = 'workspace Postico'
alt-ctrl-cmd-d = 'workspace Deskpad'
alt-ctrl-cmd-r = 'workspace Reclaim'
alt-ctrl-cmd-t = 'workspace Tools'
alt-ctrl-cmd-e = 'workspace EverythingElse'

alt-shift-cmd-ctrl-a = 'move-node-to-workspace Arc'
alt-shift-cmd-ctrl-s = 'move-node-to-workspace Slack'
alt-shift-cmd-ctrl-g = 'move-node-to-workspace Ghostty'
alt-shift-cmd-ctrl-m = 'move-node-to-workspace Messaging'
alt-shift-cmd-ctrl-i = 'move-node-to-workspace IntelliJ'
alt-shift-cmd-ctrl-v = 'move-node-to-workspace VSCode'
alt-shift-cmd-ctrl-p = 'move-node-to-workspace Postico'
alt-shift-cmd-ctrl-d = 'move-node-to-workspace Deskpad'
alt-shift-cmd-ctrl-r = 'move-node-to-workspace Reclaim'
alt-shift-cmd-ctrl-t = 'move-node-to-workspace Tools'
alt-shift-cmd-ctrl-e = 'move-node-to-workspace EverythingElse'

[workspace-to-monitor-force-assignment]
Arc = ['main', 'built-in']
Slack = ['main', 'built-in']
Ghostty = ['DeskPad Display', 'main']
Messaging = ['main', 'built-in']
IntelliJ = ['DeskPad Display', 'main']
VSCode = ['DeskPad Display', 'main']
Postico = ['DeskPad Display', 'main']
Deskpad = ['main']
Reclaim = ['main']
Tools = ['main']
EverythingElse = ['main']

[[on-window-detected]]
if.app-name-regex-substring = 'Arc'
run = ['move-node-to-workspace Arc']

[[on-window-detected]]
if.app-name-regex-substring = 'Zen'
run = ['move-node-to-workspace Arc']

[[on-window-detected]]
if.app-name-regex-substring = 'Slack'
run = ['move-node-to-workspace Slack']

[[on-window-detected]]
if.app-name-regex-substring = "Ghostty"
run = ["move-node-to-workspace Ghostty"]

[[on-window-detected]]
if.app-name-regex-substring = 'WhatsApp'
run = ['move-node-to-workspace Messaging']

[[on-window-detected]]
if.app-name-regex-substring = 'Messages'
run = ['move-node-to-workspace Messaging']

[[on-window-detected]]
if.app-name-regex-substring = 'Intellij'
run = ['move-node-to-workspace IntelliJ']

[[on-window-detected]]
if.app-name-regex-substring = 'Code'
run = ['move-node-to-workspace VSCode']

[[on-window-detected]]
if.app-name-regex-substring = 'Todoist'
run = ['move-node-to-workspace Tools']

[[on-window-detected]]
if.app-name-regex-substring = 'Reclaim'
run = ['move-node-to-workspace Reclaim']

[[on-window-detected]]
if.app-name-regex-substring = 'Postico'
run = ['move-node-to-workspace Postico']

[[on-window-detected]]
if.app-name-regex-substring = 'Deskpad'
run = ['layout tiling', 'move-node-to-workspace Deskpad']

[[on-window-detected]]
if.app-name-regex-substring = 'Google Gemini'
run = ['move-node-to-workspace Tools']

[[on-window-detected]]
if.app-id = "com.1password.1password"
run = ['layout floating']

[[on-window-detected]]
if.app-name-regex-substring = 'Gmail'
run = ['move-node-to-workspace Reclaim']

[[on-window-detected]]
if.app-name-regex-substring = 'Music'
run = ['move-node-to-workspace Tools']

[[on-window-detected]]
if.app-name-regex-substring = 'MOTIV Mix'
run = ['move-node-to-workspace EverythingElse']

[[on-window-detected]]
if.app-name-regex-substring = 'CatoClient'
run = ['move-node-to-workspace EverythingElse']
